### ISSUE TITLE
Subscribe to channel returns 400 error

### ISSUE THREAD

**Issue by DigNZ** [sidiabale/parse4cn1#12]
I'm trying to subscribe to channels in the simulator I can see the network request is returning a status code 400 (and no response body).  On Android devices I can see in the installations in Parse that channels are not being subscribed to.

Any things I need to be aware of to make this work?

**Comment by sidiabale** [comment]
Hi,

It should just work as it does in the parse4cn1 test app.

How are you trying to subscribe to channels? The right way is to use one of the subscription methods in [ParseInstallation](https://github.com/sidiabale/parse4cn1/blob/master/src/com/parse4cn1/ParseInstallation.java).

You mentioned trying in the simulator... Does that mean you're trying to subscribe to channels for an existing installation (because creating installations in the simulator should fail anyway as it's delegated to the native SDKs which means that it will only be possible on actual devices)?

If you can provide some more information on what you're doing and how you're trying to do it, maybe I could be of more help.

PS: To get more detailed error information, you can:
1. Set log level to debug (`Logger.setLogLevel(Log.DEBUG)`) _and_
2. Use `Logger.getLogContent()` or `Logger.showLog()` to view the full log including network request and response details. This will work on both simulator and device.

**Comment by DigNZ** [comment]
Hi,

I worked out a few things and I think that's got it sorted:

1.  On the simulator you need to set the Installation ID, I did this by 
adding a dummy record into the installations in parse and setting the ID 
that matched.
2.  You can't have channels that start with a number - the error message 
with the 400 response code clearly says this though the network monitor 
in CN1 doesn't seem to show the response body for responses with error 
codes so this was blank.
3.  Number 2 applies to subscribing and sending and if one channel you 
are sending to has a number then none of them will get a notification.  
I'm upgrading a product that had different (numeric) based system for 
identifying individual users, I need to update this and ensure that no 
numeric IDs are ever used as channels.


Fixing these has got us up and running for Android (and sending from the 
simulator).  On to iOS...

Cheers,
Nick


On 29/11/15 10:20, Chidiebere Okwudire wrote:
>
> Hi,
>
> It should just work as it does in the parse4cn1 test app.
>
> How are you trying to subscribe to channels? The right way is to use 
> one of the subscription methods in ParseInstallation 
> <https://github.com/sidiabale/parse4cn1/blob/master/src/com/parse4cn1/ParseInstallation.java>.
>
> You mentioned trying in the simulator... Does that mean you're trying 
> to subscribe to channels for an existing installation (because 
> creating installations in the simulator should fail anyway as it's 
> delegated to the native SDKs which means that it will only be possible 
> on actual devices)?
>
> If you can provide some more information on what you're doing and how 
> you're trying to do it, maybe I could be of more help.
>
> PS: To get more detailed error information, you can:
> 1. Set log level to debug (|Logger.setLogLevel(Log.DEBUG)|) /and/
> 2. Use |Logger.getLogContent()| or |Logger.showLog()| to view the full 
> log including network request and response details. This will work on 
> both simulator and device.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sidiabale/parse4cn1/issues/12#issuecomment-160336029>.
>

-- 
*Nick Koirala*
LittleMonkey Ltd
PO Box 13057, Johnsonville
Wellington, New Zealand
0800 356 783
+64 (0) 4 974 5574
www.littlemonkey.co.nz <http://www.littlemonkey.co.nz>

**Comment by sidiabale** [comment]
Hi Nick,

Glad to hear you've made progress. 

Re:
1. That's indeed the way to test out things in the simulator. I do the same in the  names
2. You should normally see the response code and message from Parse even when the call fails with a HTTP response different from 200. Usually, that's wrapped around in a ParseException. Anyway, you found out what the problem was so that's not a big deal. Just something to bear in mind in the future
3. I didn't know about that constraint on channels but glad you can work around it.

iOS is somewhat more challenging but still doable. Let me know if you run into any problems there.

Cheers
