### ISSUE TITLE
Parse not initialized error on Android

### ISSUE THREAD

**Issue by jegesh** [sidiabale/parse4cn1#18]
So far I've only tested my app on an Android device, and I consistently get an exception: 'Parse is not initialized' when trying to get a handle on the parse installation id from my cn1 code.  The app registers the installation with the backend (from the native Android code) just fine, and I am able to receive push notifications (sent to a wide audience).  When I try to call `ParseInstallation.getCurrentInstallation()` or `parseObj.save()`, it raises the exception.  The backend is a hosted parse server solution by back4app.com, although it shouldn't make any difference, especially since I seem to remember having this problem even before I migrated the app from parse.com.

**Comment by sidiabale** [comment]
Hi,

parse4cn1's push implementation currently only supports and is tested with
Parse.com. The included native SDKs predate the open source Parse server. I
don't know how back4app handles push but the first step would be to first
confirm if push works via Parse.com.

I'm in the process of upgrading parse4cn1 for the open source Parse server
but I doubt push notifications will be part of my first update scheduled
for end of May/June. If you need this fast, consider implementing it
yourself and issuing a PR.

All the best.

**Comment by jegesh** [comment]
No, as I stated in my first comment, I have no trouble receiving pushes, the problem is just getting the installation id from the cn1 code.  This, as far as I can tell, is not related to the backend at all, since the error message I get is coming from the Android parse library, and since I had the same problem using the original parse.com hosted backend.

**Comment by sidiabale** [comment]
I think I understand what's happening: You're getting the "Parse is not
initialized" exception
<https://github.com/sidiabale/parse4cn1/blob/master/src/com/parse4cn1/ParseInstallation.java#L391>,
right? The current implementation
<https://github.com/sidiabale/parse4cn1/blob/master/src/com/parse4cn1/Parse.java#L235>
checks if both your applicationKey and clientId are set. That was required
for Parse.com but the clientKey is optional in Parse Server. This is one of
the changes I'll make in the upgrade for Parse Server. For now, I suggest
you try setting a non-empty, non-null clientKey in your Parse.initialize()
call.

Let me know if that helps.

**Comment by jegesh** [comment]
No, unfortunately, that's not it.  I have been using both app key and client ID the whole time.  But that is the exception I get, indeed.

**Comment by sidiabale** [comment]
That's strange. That exception is thrown only in one place and only if
Parse.initialized() returns false. The implementation is very
straightforward (see below) so something must be going wrong somewhere. It
seems your application ID or client key is not reset (or gets reset). Can
you go through your code and make sure you're not missing something?

return (getApplicationId() != null && getApplicationId().length() > 0
   && getClientKey() != null && getClientKey().length() > 0);

**Comment by sidiabale** [comment]
Hi,

Did you manage to figure out what was going wrong? Is the problem solved?

**Comment by sidiabale** [comment]
Closing issue as reporter has provided no updates and I could not reproduce it with tests against the same backend (back4apps)

**Comment by jegesh** [comment]
Hi, thanks for your persistence.  I'm sorry I didn't answer your last inquiry promptly, I was too busy to work on this particular issue.  I have made some progress, however, and my initial problem, it turned out, was that I thought the SDK initialization in the native Android code was sufficient, I didn't realize it needs to be initialized in the cn1 code as well.

At the moment, I'm getting hung up on an almost identical issue, but I now know more about the problem.  Currently, my code trips up when I try to get a handle on `currentInstallation`.  Here's the relevant part of the stack trace:
```
07-19 03:31:26.936 21922-21954/? W/System.err: ParseException [code=-3, msg=Failed to retrieve installation ID, cause=null]
07-19 03:31:26.936 21922-21954/? W/System.err:     at com.parse4cn1.ParseInstallation.retrieveObjectId(ParseInstallation.java:438)
07-19 03:31:26.936 21922-21954/? W/System.err:     at com.parse4cn1.ParseInstallation.getCurrentInstallation(ParseInstallation.java:81)
```

This happens even though the Android code returns a positive message, and in `initVars()` the parse SDK is successfully initialized.  Do you have any idea what's causing the problem now?

**Comment by sidiabale** [comment]
Hi, good to hear that you made progress on the first issue. Are you running against Parse.com or a Parse Server backend?

**Comment by jegesh** [comment]
Parse server, hosted by back4apps

**Comment by sidiabale** [comment]
back4apps means you're using parse4cn1 version 3.0 right? If that's the case, I don't understand how you're able to create installations in the first place because I've not updated the native android library yet and so native lookup fails.  Did you make any changes e.g. upgrade the android parse SDK used by parse4cn1? Please provide me with as much information as possible about your configuration so I can assist you better.

**Comment by jegesh** [comment]
I may have made a silly mistake.  I'll tell you what I did.  I read that your latest release of the lib doesn't support push notifications, and I had previously been using release v2.0, with which I was getting odd errors and was able to push only from the console, although the library installed properly and I was getting deviceId and installationId properly in the db.  I saw that release 3.0 specifically supported parse server, so I installed it in my project, without removing the previous version of the lib (although I changed its name so that it wouldn't be overwritten).  I'm not sure what exactly is supposed to happen when you install a different version of the same library on top of a previous one, but I figured maybe it would just override the files that had changed.  In any case, I'm no closer to a solution than before.  Maybe you can give me some guidance and I can help you make the necessary changes to support push with parse server?

**Comment by sidiabale** [comment]
Hi, thanks for the update. As far as I know, the version 3.0 will replace version 2.0 if you have both (and have changed the name of the latter). That also explains why it says the native code is not implemented because that's the case in version 3.0. 

What's your time frame for getting this up and running? I would also like to see it working but I'm very busy with other things now. Moreover, in the [announcement](https://www.smash-ict.com/blog/announcements/parse4cn1-is-now-parse-server-ready/) of version 3.0, I included a form to see how many people really need this feature soon and so far, I got only one response so it seems to kinda low prio at the moment... If I get at least 5 persons showing interest, I'll raise the priority and schedule it earlier.

In any case, what needs to happen to get this working for Android (from the top of my head) is:

- Fork parse4cn1 if you already haven't done so
- Update the native Android Parse SDK to a version that supports Parse Server. You can find instructions [here](https://github.com/sidiabale/parse4cn1/blob/ca3a8b246b6f45e029d7620cdfd12256e2c1e68d/native/android/Integrating_Parse_Android_SDK.md)
- Implement the intiialization function in the Android native code similar the [old implementation](https://github.com/sidiabale/parse4cn1/blob/ca3a8b246b6f45e029d7620cdfd12256e2c1e68d/native/android/com/parse4cn1/nativeinterface/ParseInstallationNativeImpl.java) but this time also passing your backend URL

That should solve get things up and running. Please give it a shot and let me know if you get stuck. Do not forget to issue a PR if you succeed.

**Comment by jegesh** [comment]
Ok, I'm on it!

**Comment by jegesh** [comment]
For the record, the problem was that I wasn't initializing Parse in the cn1 code, just in the native Android code. I hadn't realized that both were necessary.
