### ISSUE TITLE
Issue concerning ParseFile (image file) saved on back4app server

### ISSUE THREAD

**Issue by fil00dl** [sidiabale/parse4cn1#20]
Hello,

I saw you have been writing about replacement for parse.com, it is a great initiative and appreciated your article (for information I chose back4app which is really attractive).

However I meet an issue since I updated the last version of parse4cn1 library in my CN1 project (and initialize with new URL https://parseapi.back4app.com).

The problem is that ParseFile (especially PNG and JPG files) are saved through an incorrect format, see example here : https://parsefiles.back4app.com/4QXICdDIV33YzmAZatwXwMHGaM4NiwqldZfExu5A/1705c1eec293c5749cf5d925a3d4a280_avatar.png

My code hasn’t changed since the parse server migration :
ParseFile imgFile = new ParseFile("avatar.png", encImg.getImageData(), "image/png »);
imgFile.save();
ParseObject uploadObject = ParseObject.create("Upload");
uploadObject.save();

It seems that there is an issue of content-type but when I upload directly a picture into parse-dashboard, it works well. 
The issue might come from ParseFile object but I don’t know how to solve it. Have you got any idea about that?

Thank you very much in advance for your help.

P.S : Sorry for my english, it’s not my native language.

**Comment by sidiabale** [comment]
Hi,

Nice to hear that someone found the articles useful. I'll investigate the issue though my first guess is that it's not a back4app problem but a Parse Server issue. I'll update you as soon as I know more.

Cheers

**Comment by sidiabale** [comment]
Hi,

I tried downloading the example image again and it now seems to work fine. Did you manage to fix the problem? If so, can you share your solution here?

**Comment by fil00dl** [comment]
Unfortunately I am still stuck on this issue.
Please take a look at my function below (which worked well on parse.com, also on the previous version of parse4cn1 with back4app).


    public void savePhoto(Image img) throws ParseException {
        ParseUser currentUser = ParseUser.getCurrent();
        EncodedImage encImg = null;
        if (img instanceof EncodedImage) {
            encImg = (EncodedImage) img;
        } else {
            encImg = EncodedImage.createFromImage(img, false);
            encImg = encImg.scaledEncoded(512, 512);
        }
        ParseFile imgFile = new ParseFile("avatar.png", encImg.getImageData(), "image/png");
        imgFile.save();
   
        ParseObject uploadObject = ParseObject.create("Upload");
        uploadObject.put("file", imgFile);
        uploadObject.save();

        currentUser.put("avatar", imgFile);
        currentUser.save();
        
        System.out.println(imgFile.toString()+ " -- " + imgFile.getName());
        //it displays : com.parse4cn1.ParseFile@1c069c4a -- c3ed61fdda7e5591c77ecfab50642285_avatar.png
    }

The result of saved parseFile image is very weird : The name of the file is truncated on ParseDashboard (It should be "avatar.png")

![screenshot](https://cloud.githubusercontent.com/assets/13983024/17937321/f4ea107e-6a21-11e6-923b-3759aa612ab6.png) 
as well as opening images directly via the dashboard (link example : https://parsefiles.back4app.com/4QXICdDIV33YzmAZatwXwMHGaM4NiwqldZfExu5A/1705c1eec293c5749cf5d925a3d4a280_avatar.png), so therefore Codename One does not recognize the picture format.


I noticed that the problem occurred since that images (ParseFiles) are recorded via HTTPS (with the previous version of parse4cn1, photos were well saved both on parse.com and back4app server via HTTP).

Do you have an example image code sample that works for you that I can try?
Thank you very much.

**Comment by sidiabale** [comment]
Hi,

I'm currently very busy which is why I've not had the time to look into this issue in detail. In any case, I need clarification from you.

1. What happens if you save your encoded image to disc? Does it display properly?
2. Did you contact back4app about this?
3. What version of parse4cn1 are you using? You referred to a previous version that worked also for back4app... That is strange cos I've released only one version that is Parse Server compatible and that is version 3.0. So what other version were you referring to?
4. What versions of Parse Server and Parse Dashboard are you running against in your back4app backend?
5. Have you made any customizations to parse4cn1?

Please provide any additional information that you think might be useful so that if I can find the time this week, my investigation will be focused.

Your best bet for now would be to clone the repo and build parse4cn1 locally os you can debug better if you're convinced that it's a parse4cn1 issue (though I doubt). The steps are described in the README of this repo and should be quite straightforward.

In terms of sample code, there is a ParseFile unit test that amongst others uploads an image to the backend, retrieves it and checks for binary compatibility. You can find it [here](https://github.com/sidiabale/parse4cn1/blob/master/test/CN1TestApp/test/com/parse4cn1/ParseFileTest.java#L79). The test passed at the time I released v3.0 and I've not made any changes since then. That's why I guess this is an issue with Parse Server itself and not parse4cn1 but that needs to be confirmed.

Cheers

**Comment by fil00dl** [comment]
I finally found the solution to my issue. 

This is on my side : I use the substring method on the ParseFile URL in order to name the photo. 
But since ParseFile images are stored on back4app server, the URL is necessarily not the same than on parse.com (I used the substring “tfss”), this explains that.

Sorry for the inconvenience and thank you for your time.

Cheers

**Comment by alambertt** [comment]
Hi, I have the same trouble with images (png anf JPG). PLease, any solution until now?? I even use the Postman to make the request and I got the same result that @fil00dl with the image response.

**Comment by sidiabale** [comment]
Hi, this is a very old thread for which I never received feedback to
further investigate. However, the fact that it fails when using Postman
confirms that this issue is not with parse4cn1 but most likely Parse
Server. I suggest you reach out to the guys at Back4App. They might be able
to help you. If you do find a solution, please remember to update this
thread.

**Comment by alambertt** [comment]
VICTORY!!!!! I SOLVED USING THIS COMPONENT FOR ANGULAR 

https://github.com/AckerApple/angular-file

It seems that there was a problem with the file on the REST request that the way I was doing it and even using the Postman was wrong.
When using this component I found it perfectly. I recommend it for handling files with Angular and forms.

**Comment by sidiabale** [comment]
Great to hear. Cheers!

Op za 5 okt. 2019 06:35 schreef Angel Lambertt Pierra <
notifications@github.com>:
